import { useState, useCallback } from 'react';
import { Download, Mail, Printer } from 'lucide-react';
import { Layout } from '../components/Layout';
import { useAuth } from '../context/AuthContext';
import { readSheet } from '../lib/sheets';
import { parseSheetNumber, parseSheetPercentage } from '../lib/values';
import { useCoachName } from '../hooks/useCoachName';
import { SHEET_ID, TABS } from '../config';

function buildMonths(count: number) {
  const current = new Date();
  return Array.from({ length: count }, (_, index) => {
    const date = new Date(current.getFullYear(), current.getMonth() - count + index + 1, 1);
    const shortMonth = date.toLocaleString('en-US', { month: 'short' });
    const longMonth = date.toLocaleString('en-US', { month: 'long' });
    const year = date.getFullYear();
    return {
      label: `${longMonth} ${year}`,
      shortLabel: `${shortMonth} '${String(year).slice(-2)}`,
      feeKey: `${year}-${String(date.getMonth() + 1).padStart(2, '0')}`,
      matchKeys: [`${shortMonth}-${year}`, `${shortMonth} ${year}`, `${longMonth} ${year}`].map(key => key.toLowerCase()),
    };
  });
}

const MONTHS = buildMonths(24);

function matchesMonth(value: string, month: typeof MONTHS[number]) {
  const normalized = value.trim().toLowerCase();
  return normalized.includes(month.feeKey) || month.matchKeys.some(key => normalized.includes(key));
}

const MEDAL_ICON: Record<string, string> = {
  Gold: '🥇', Silver: '🥈', Bronze: '🥉', 'Best Game': '⭐', Participation: '🎖',
};

const FEE_COLOR: Record<string, string> = {
  Paid: 'badge-green', Partial: 'badge-amber', Pending: 'badge-amber',
  Overdue: 'badge-red', Waived: 'badge-gray',
};

export interface StudentReport {
  name: string;
  batch: string;
  daysAttended: number;
  daysScheduled: number;
  attendancePct: number;
  feeStatus: string;
  feeBalance: string;
  medals: string[];
  overallRating: string;
  openingSkill: string;
  middlegameSkill: string;
  endgameSkill: string;
  tacticsSkill: string;
  sportsmanship: string;
  prize: string;
  coachSummary: string;
  parentMeeting: string;
}

export function MonthlyReport() {
  const { token, logout } = useAuth();
  const { coachName: savedCoachName } = useCoachName();
  const [selectedMonth, setSelectedMonth] = useState(MONTHS.length - 1);
  const [reports, setReports] = useState<StudentReport[]>([]);
  const [loading, setLoading] = useState(false);
  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState('');
  const [expandedName, setExpandedName] = useState<string | null>(null);
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [emailTo, setEmailTo] = useState('');
  const [emailCc, setEmailCc] = useState('');
  const [emailError, setEmailError] = useState('');
  const coachName = savedCoachName || 'Admin';
  const attendanceReports = reports.filter(report => report.daysScheduled > 0);
  const avgAttendance = attendanceReports.length
    ? Math.round(attendanceReports.reduce((sum, report) => sum + report.attendancePct, 0) / attendanceReports.length * 100)
    : null;
  const avgAttendanceLabel = avgAttendance === null ? 'N/A' : `${avgAttendance}%`;

  const generateReportText = () => {
    const month = MONTHS[selectedMonth].label;
    const today = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
    const atRisk = reports.filter(r => r.daysScheduled > 0 && r.attendancePct < 0.5);
    const pending = reports.filter(r => r.feeStatus && r.feeStatus !== 'Paid' && r.feeStatus !== 'Waived');
    let t = `KAFT Chess Academy — Monthly Report: ${month}\nGenerated: ${today} by ${coachName}\n`;
    t += `${'='.repeat(50)}\n\nSUMMARY\n${'─'.repeat(30)}\n`;
    t += `Total Students : ${reports.length}\nAvg Attendance : ${avgAttendanceLabel}\n\n`;
    if (atRisk.length) {
      t += `⚠️  LOW ATTENDANCE (below 50%)\n${'─'.repeat(30)}\n`;
      atRisk.forEach(r => { t += `${r.name} — ${r.daysAttended}/${r.daysScheduled} days (${Math.round(r.attendancePct*100)}%)\n`; });
      t += '\n';
    }
    if (pending.length) {
      t += `💰  PENDING / OVERDUE FEES\n${'─'.repeat(30)}\n`;
      pending.forEach(r => { t += `${r.name} — ${r.feeStatus}${r.feeBalance ? ` ₹${r.feeBalance}` : ''}\n`; });
      t += '\n';
    }
    t += `📅  FULL ATTENDANCE\n${'─'.repeat(30)}\n`;
    reports.forEach(r => {
      const pct = Math.round(r.attendancePct * 100);
      t += `${pct>=75?'✅':pct>=50?'⚠️':'❌'} ${r.name.padEnd(22)} ${r.daysAttended}/${r.daysScheduled} days  ${pct}%\n`;
    });
    t += `\n${'─'.repeat(50)}\nThis report was auto-generated by the KAFT Chess Academy App.`;
    return t;
  };

  const handleSendEmail = () => {
    if (!emailTo.trim()) return;
    const addresses = [emailTo.trim(), emailCc.trim()].filter(Boolean);
    const isEmail = (address: string) => {
      const at = address.indexOf('@');
      const dot = address.lastIndexOf('.');
      return address.trim() === address && !address.includes(' ') && at > 0
        && at === address.lastIndexOf('@') && dot > at + 1 && dot < address.length - 1;
    };
    if (addresses.some(address => !isEmail(address))) {
      setEmailError('Enter valid email addresses before opening the report.');
      return;
    }
    setEmailError('');
    const subject = `KAFT Chess Academy — Monthly Report: ${MONTHS[selectedMonth].label}`;
    const body = generateReportText();
    const url = `mailto:${emailTo.trim()}${emailCc.trim() ? `?cc=${emailCc.trim()}&` : '?'}subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(url, '_blank');
    setShowEmailModal(false);
  };

  const load = useCallback(async (monthIdx: number) => {
    if (!token) return;
    setLoading(true); setError(''); setLoaded(false); setReports([]);
    const month = MONTHS[monthIdx];
    try {
      const [studentRows, attRows, feeRows, tornRows, metricsRows] = await Promise.all([
        readSheet(token, SHEET_ID, `'${TABS.STUDENTS}'!A:I`),
        readSheet(token, SHEET_ID, `'${TABS.MONTHLY_ATT}'!A:E`),
        readSheet(token, SHEET_ID, `'${TABS.FEES}'!B:L`),
        readSheet(token, SHEET_ID, `'${TABS.TOURNAMENTS}'!A:Q`),
        readSheet(token, SHEET_ID, `'${TABS.METRICS}'!A:O`),
      ]);

      // Attendance rows: A=Name, B=Month(formatted), C=DaysAttended, D=Scheduled, E=Pct
      const attMap = new Map<string, { days: number; scheduled: number; pct: number }>();
      attRows.slice(1).forEach(r => {
        const name = r[0]?.trim();
        const rowMonth = r[1]?.trim() ?? '';
        if (!name || !matchesMonth(rowMonth, month)) return;
        attMap.set(name, {
          days:      parseSheetNumber(r[2]),
          scheduled: parseSheetNumber(r[3]),
          pct:       parseSheetPercentage(r[4]),
        });
      });

      // Fee rows: B=StudentName(0), D=FeeMonth(2→col index 2 in slice), L=Status(10)
      // readSheet returns: [B,C,D,E,F,G,H,I,J,K,L] → index: Name=0,Batch=1,Month=2,...,Status=10,Balance=6
      const feeMap = new Map<string, { status: string; balance: string }>();
      feeRows.slice(1).forEach(r => {
        const name = r[0]?.trim();
        const rowMonth = r[2]?.trim() ?? ''; // D col = index 2
        if (!name || !matchesMonth(rowMonth, month)) return;
        const existing = feeMap.get(name);
        const status = r[10]?.trim() ?? '';
        // worst status wins
        const priority = ['Overdue','Partial','Pending','Paid','Waived'];
        const existingPriority = existing ? priority.indexOf(existing.status) : Number.MAX_SAFE_INTEGER;
        const statusPriority = priority.indexOf(status);
        feeMap.set(name, {
          status: !existing || (statusPriority >= 0 && statusPriority < existingPriority) ? status : existing.status,
          balance: String(parseSheetNumber(existing?.balance) + parseSheetNumber(r[6])),
        });
      });

      // Tournament rows: A=Month(0), B=Name(1), Q=Medal(16)
      const tornMap = new Map<string, string[]>();
      tornRows.slice(1).forEach(r => {
        const name = r[1]?.trim();
        const rowMonth = r[0]?.trim() ?? '';
        const medal = r[16]?.trim() ?? '';
        if (!name || !matchesMonth(rowMonth, month) || !medal || medal === 'None') return;
        if (!tornMap.has(name)) tornMap.set(name, []);
        tornMap.get(name)!.push(medal);
      });

      // Metrics rows: A=Name(0), B=Month(1), C=Batch(2), D=AttPct(3),
      //               E=Opening(4) F=Mid(5) G=End(6) H=Tactics(7) I=Sport(8)
      //               J=Overall(9) K=Prize(10) L=PrizeDetail(11) M=CoachSummary(12) N=ParentMeeting(13)
      const metricsMap = new Map<string, { batch:string; overall:string; opening:string; mid:string; end:string; tactics:string; sport:string; prize:string; coach:string; parent:string }>();
      metricsRows.slice(1).forEach(r => {
        const name = r[0]?.trim();
        const rowMonth = r[1]?.trim() ?? '';
        if (!name || !matchesMonth(rowMonth, month)) return;
        metricsMap.set(name, {
          batch: r[2]??'', overall: r[9]??'', opening: r[4]??'', mid: r[5]??'',
          end: r[6]??'', tactics: r[7]??'', sport: r[8]??'',
          prize: r[10]??'', coach: r[12]??'', parent: r[13]??'',
        });
      });

      const studentMap = new Map<string, string>();
      studentRows.slice(1).forEach(row => {
        const name = row[0]?.trim();
        if (name) studentMap.set(name, row[5]?.trim() ?? '');
      });
      attMap.forEach((_, name) => { if (!studentMap.has(name)) studentMap.set(name, ''); });

      // Build the report from the roster and left-join monthly data.
      const result: StudentReport[] = [];
      studentMap.forEach((rosterBatch, name) => {
        const att = attMap.get(name) ?? { days: 0, scheduled: 0, pct: 0 };
        const fee = feeMap.get(name);
        const medals = tornMap.get(name) ?? [];
        const m = metricsMap.get(name);
        result.push({
          name, batch: m?.batch || rosterBatch,
          daysAttended: att.days, daysScheduled: att.scheduled,
          attendancePct: att.pct,
          feeStatus: fee?.status ?? '', feeBalance: fee?.balance ?? '',
          medals, overallRating: m?.overall ?? '',
          openingSkill: m?.opening ?? '', middlegameSkill: m?.mid ?? '',
          endgameSkill: m?.end ?? '', tacticsSkill: m?.tactics ?? '',
          sportsmanship: m?.sport ?? '', prize: m?.prize ?? '',
          coachSummary: m?.coach ?? '', parentMeeting: m?.parent ?? '',
        });
      });

      result.sort((a, b) => b.attendancePct - a.attendancePct);
      setReports(result);
      setLoaded(true);
    } catch (e: any) {
      if (e.message === 'TOKEN_EXPIRED') { logout(); return; }
      setError(e.message);
    } finally { setLoading(false); }
  }, [token, logout]);

  const handleMonthChange = (idx: number) => {
    setSelectedMonth(idx);
    setLoaded(false); setReports([]);
  };

  const downloadPdf = async () => {
    const { downloadMonthlyPerformancePdf } = await import('../lib/monthlyReportPdf');
    downloadMonthlyPerformancePdf({
      month: MONTHS[selectedMonth].label,
      coachName,
      reports,
    });
  };

  return (
    <Layout title="Monthly Report" showBack action={
      loaded ? (
        <div className="flex gap-1 no-print">
          <button type="button" onClick={() => { setEmailError(''); setShowEmailModal(true); }} className="header-action px-2" aria-label="Email report" title="Email report"><Mail size={15} aria-hidden="true" /></button>
          <button type="button" onClick={downloadPdf} className="header-action"><Download size={15} aria-hidden="true" /> PDF</button>
          <button type="button" onClick={() => window.print()} className="header-action px-2" aria-label="Print report" title="Print report"><Printer size={15} aria-hidden="true" /></button>
        </div>
      ) : undefined
    }>
      <div className="p-4 space-y-3">
        {/* Month selector */}
        <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-4">
          <p className="text-xs font-medium text-gray-500 mb-2">Select Month</p>
          <div className="flex gap-2 overflow-x-auto pb-1 no-scrollbar">
            {MONTHS.map((m, i) => (
              <button key={i} onClick={() => handleMonthChange(i)}
                className={`flex-shrink-0 px-3 py-2 rounded-xl text-xs font-semibold transition-colors
                  ${selectedMonth === i ? 'bg-navy text-white' : 'bg-gray-100 text-gray-600'}`}>
                {m.shortLabel}
              </button>
            ))}
          </div>
          <button onClick={() => load(selectedMonth)} disabled={loading}
            className="mt-3 w-full bg-chess-blue text-white py-2.5 rounded-xl text-sm font-semibold disabled:opacity-50">
            {loading ? 'Loading…' : `Load ${MONTHS[selectedMonth].label} Report`}
          </button>
        </div>

        {error && <p className="text-red-600 text-sm bg-red-50 p-3 rounded-xl">{error}</p>}

        {loaded && (
          <>
            {/* Summary bar */}
            <div className="grid grid-cols-3 gap-2">
              <SumCard label="Students" value={reports.length} color="bg-navy text-white" />
              <SumCard label="Avg Attendance"
                value={avgAttendance === null ? '—' : avgAttendanceLabel}
                color="bg-chess-blue text-white" />
              <SumCard label="Achievements" value={reports.reduce((s,r)=>s+r.medals.length,0)} color="bg-purple-600 text-white" />
            </div>

            {/* At-risk section */}
            {reports.filter(r => r.daysScheduled > 0 && r.attendancePct < 0.5).length > 0 && (
              <div className="bg-red-50 border border-red-200 rounded-xl p-3">
                <p className="text-red-700 text-xs font-bold mb-1">⚠️ Below 50% Attendance</p>
                {reports.filter(r => r.daysScheduled > 0 && r.attendancePct < 0.5).map(r => (
                  <p key={r.name} className="text-red-600 text-sm">{r.name} — {Math.round(r.attendancePct * 100)}%</p>
                ))}
              </div>
            )}

            {/* Student cards */}
            {reports.length === 0 && (
              <p className="text-center text-gray-400 py-8">No data for this month yet.</p>
            )}
            {reports.map(r => {
              const pct = Math.round(r.attendancePct * 100);
              const attColor = pct >= 75 ? 'bg-green-500' : pct >= 50 ? 'bg-amber-400' : 'bg-red-500';
              const expanded = expandedName === r.name;
              return (
                <div key={r.name} className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
                  {/* Card header */}
                  <button onClick={() => setExpandedName(expanded ? null : r.name)}
                    className="w-full p-4 text-left flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <p className="font-semibold text-gray-900">{r.name}</p>
                        {r.batch && <span className="badge-blue">{r.batch}</span>}
                        {r.medals.map((m, i) => <span key={i} className="text-lg">{MEDAL_ICON[m] ?? '🎖'}</span>)}
                        {r.parentMeeting === 'Yes' && <span className="badge-red">Parent Meet</span>}
                      </div>
                      {/* Attendance bar */}
                      <div className="mt-2">
                        <div className="flex justify-between text-xs text-gray-500 mb-1">
                          <span>📅 {r.daysAttended}/{r.daysScheduled} days</span>
                          <span className={`font-bold ${pct>=75?'text-green-600':pct>=50?'text-amber-600':'text-red-600'}`}>{pct}%</span>
                        </div>
                        <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                          <div className={`h-full ${attColor} rounded-full`} style={{ width: `${Math.min(pct,100)}%` }} />
                        </div>
                      </div>
                      {/* Fee + quick stats row */}
                      <div className="flex gap-2 mt-2 flex-wrap">
                        {r.feeStatus && <span className={FEE_COLOR[r.feeStatus] ?? 'badge-gray'}>💰 {r.feeStatus}</span>}
                        {r.feeStatus === 'Overdue' && r.feeBalance && <span className="text-xs text-red-500">₹{r.feeBalance} due</span>}
                        {r.overallRating && <span className="badge-blue">⭐ {parseFloat(r.overallRating).toFixed(1)}/5</span>}
                        {r.prize && <span className="badge-green">🏅 {r.prize}</span>}
                      </div>
                    </div>
                    <span className={`ml-2 text-gray-300 text-xl transition-transform ${expanded ? 'rotate-90' : ''}`}>›</span>
                  </button>

                  {/* Expanded details */}
                  {expanded && (
                    <div className="border-t border-gray-100 p-4 bg-gray-50 space-y-3">
                      {/* Skill ratings */}
                      {(r.openingSkill || r.middlegameSkill || r.endgameSkill) && (
                        <div>
                          <p className="text-xs font-bold text-navy mb-2">SKILL RATINGS</p>
                          <div className="grid grid-cols-3 gap-2">
                            {[['Opening', r.openingSkill],['Middlegame', r.middlegameSkill],
                              ['Endgame', r.endgameSkill],['Tactics', r.tacticsSkill],
                              ['Sportsmanship', r.sportsmanship]].filter(([,v])=>v).map(([label, val]) => (
                              <div key={label} className="bg-white rounded-lg p-2 text-center border border-gray-100">
                                <p className="text-xs text-gray-500">{label}</p>
                                <p className="font-bold text-navy text-lg">{val}<span className="text-xs text-gray-400">/5</span></p>
                                <div className="flex justify-center gap-0.5 mt-1">
                                  {[1,2,3,4,5].map(n => (
                                    <div key={n} className={`w-2 h-2 rounded-full ${n<=parseFloat(val??'0')?'bg-chess-blue':'bg-gray-200'}`} />
                                  ))}
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                      {/* Coach summary */}
                      {r.coachSummary && (
                        <div className="bg-white rounded-xl p-3 border border-gray-100">
                          <p className="text-xs font-bold text-navy mb-1">COACH NOTES</p>
                          <p className="text-sm text-gray-700">{r.coachSummary}</p>
                        </div>
                      )}
                      {/* Tournaments */}
                      {r.medals.length > 0 && (
                        <div className="bg-white rounded-xl p-3 border border-gray-100">
                          <p className="text-xs font-bold text-navy mb-1">ACHIEVEMENTS</p>
                          <div className="flex gap-2 flex-wrap">
                            {r.medals.map((m, i) => (
                              <span key={i} className="text-sm">{MEDAL_ICON[m] ?? '🎖'} {m}</span>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </>
        )}
      </div>

      {/* Email modal */}
      {showEmailModal && (
        <div className="fixed inset-0 bg-black/50 flex items-end z-50 no-print" onClick={() => setShowEmailModal(false)}>
          <div className="bg-white w-full rounded-t-2xl p-5" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <h2 className="font-bold text-lg text-navy">📧 Send Monthly Report</h2>
              <button onClick={() => setShowEmailModal(false)} className="text-gray-400 text-2xl leading-none">×</button>
            </div>
            <p className="text-xs text-gray-500 mb-3">
              Opens your Gmail app with the full {MONTHS[selectedMonth].label} report pre-filled. Just tap Send.
            </p>
            {emailError && <p className="text-sm text-red-600 bg-red-50 rounded-xl p-3 mb-3">{emailError}</p>}
            <div className="space-y-3">
              <div>
                <label className="text-xs font-medium text-gray-500 mb-1 block">To (required) *</label>
                <input value={emailTo} onChange={e => setEmailTo(e.target.value)}
                  type="email" placeholder="e.g. principal@kaftchess.com"
                  className="input w-full" autoFocus />
              </div>
              <div>
                <label className="text-xs font-medium text-gray-500 mb-1 block">CC (optional — add more coaches)</label>
                <input value={emailCc} onChange={e => setEmailCc(e.target.value)}
                  type="email" placeholder="e.g. coach2@gmail.com"
                  className="input w-full" />
              </div>
              <div className="bg-gray-50 rounded-xl p-3 text-xs text-gray-500">
                <p className="font-semibold mb-1">Report includes:</p>
                <p>• Attendance summary ({reports.length} students, avg {avgAttendanceLabel})</p>
                <p>• Students below 50% attendance</p>
                <p>• Pending / overdue fees</p>
                <p>• Full student-by-student breakdown</p>
              </div>
            </div>
            <button onClick={handleSendEmail} disabled={!emailTo.trim()}
              className="w-full bg-navy text-white py-3 rounded-xl font-semibold mt-4 disabled:opacity-50">
              📧 Open in Gmail / Mail App
            </button>
          </div>
        </div>
      )}
    </Layout>
  );
}

function SumCard({ label, value, color }: { label: string; value: string | number; color: string }) {
  return (
    <div className={`${color} rounded-xl p-3 text-center`}>
      <p className="text-xs opacity-80">{label}</p>
      <p className="text-xl font-bold">{value}</p>
    </div>
  );
}
